CREATE TABLE "User" ("id" UUID NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "UserIdentity" ("id" UUID NOT NULL, "userId" UUID NOT NULL, "provider" TEXT NOT NULL, "providerSubject" TEXT NOT NULL, CONSTRAINT "UserIdentity_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "UserIdentity_provider_providerSubject_key" ON "UserIdentity"("provider", "providerSubject");
CREATE INDEX "UserIdentity_userId_idx" ON "UserIdentity"("userId");
ALTER TABLE "UserIdentity" ADD CONSTRAINT "UserIdentity_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO "User" ("id") SELECT DISTINCT md5('coforge:' || subject)::uuid FROM (SELECT "externalUserId" AS subject FROM "WorkspaceMembership" UNION SELECT "ownerUserId" FROM "Agent" UNION SELECT "ownerUserId" FROM "Computer") subjects;
INSERT INTO "UserIdentity" ("id", "userId", "provider", "providerSubject") SELECT md5('identity:' || subject)::uuid, md5('coforge:' || subject)::uuid, 'authing', subject FROM (SELECT "externalUserId" AS subject FROM "WorkspaceMembership" UNION SELECT "ownerUserId" FROM "Agent" UNION SELECT "ownerUserId" FROM "Computer") subjects ON CONFLICT DO NOTHING;
ALTER TABLE "WorkspaceMembership" ADD COLUMN "userId" UUID;
UPDATE "WorkspaceMembership" SET "userId" = "User"."id" FROM "User" JOIN "UserIdentity" ON "UserIdentity"."userId" = "User"."id" WHERE "UserIdentity"."provider" = 'authing' AND "UserIdentity"."providerSubject" = "WorkspaceMembership"."externalUserId";
ALTER TABLE "WorkspaceMembership" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "WorkspaceMembership" DROP CONSTRAINT "WorkspaceMembership_pkey";
DROP INDEX "WorkspaceMembership_externalUserId_idx";
ALTER TABLE "WorkspaceMembership" DROP COLUMN "externalUserId";
ALTER TABLE "WorkspaceMembership" ADD CONSTRAINT "WorkspaceMembership_pkey" PRIMARY KEY ("workspaceId","userId");
ALTER TABLE "WorkspaceMembership" ADD CONSTRAINT "WorkspaceMembership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Agent" RENAME COLUMN "ownerUserId" TO "ownerId";
ALTER TABLE "Computer" RENAME COLUMN "ownerUserId" TO "ownerId";
ALTER TABLE "Agent" ALTER COLUMN "ownerId" TYPE UUID USING md5('coforge:' || "ownerId")::uuid;
ALTER TABLE "Computer" ALTER COLUMN "ownerId" TYPE UUID USING md5('coforge:' || "ownerId")::uuid;
ALTER TABLE "Agent" ADD CONSTRAINT "Agent_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id");
ALTER TABLE "Computer" ADD CONSTRAINT "Computer_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id");
DROP INDEX "Computer_ownerUserId_machineId_key";
CREATE UNIQUE INDEX "Computer_ownerId_machineId_key" ON "Computer"("ownerId","machineId");
