/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as AppComputersRouteImport } from './routes/_app/computers'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiAgentApiKeysRouteImport } from './routes/api/agent-api-keys'
import { Route as ApiAgentMessagesRouteImport } from './routes/api/agent-messages'
import { Route as ApiAttachmentsRouteImport } from './routes/api/attachments'
import { Route as ApiJwksRouteImport } from './routes/api/jwks'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as OauthDeviceRouteImport } from './routes/oauth/device'
import { Route as OauthTokenRouteImport } from './routes/oauth/token'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents.index'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app/agents.$agentId'
import { Route as AppComputersIndexRouteImport } from './routes/_app/computers.index'
import { Route as AppComputersComputerIdRouteImport } from './routes/_app/computers.$computerId'
import { Route as AppMessagesIndexRouteImport } from './routes/_app/messages.index'
import { Route as AppMessagesAgentIdRouteImport } from './routes/_app/messages.$agentId'
import { Route as ApiAgentAttachmentUploadCapabilitiesRouteImport } from './routes/api/agent/attachment-upload-capabilities'
import { Route as ApiAttachmentsAttachmentIdRouteImport } from './routes/api/attachments.$attachmentId'
import { Route as ApiInternalCentrifugoRouteImport } from './routes/api/internal/centrifugo'
import { Route as ApiInternalCentrifugoAgentActivityRouteImport } from './routes/api/internal/centrifugo-agent-activity'
import { Route as ApiInternalCentrifugoConnectRouteImport } from './routes/api/internal/centrifugo-connect'
import { Route as ApiMeAvatarRouteImport } from './routes/api/me/avatar'
import { Route as ApiAgentAttachmentsAttachmentIdRouteImport } from './routes/api/agent/attachments.$attachmentId'
import { Route as ApiE2eWorkspacesSlugRouteImport } from './routes/api/e2e/workspaces.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppComputersRoute = AppComputersRouteImport.update({
  id: '/computers',
  path: '/computers',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiAgentApiKeysRoute = ApiAgentApiKeysRouteImport.update({
  id: '/api/agent-api-keys',
  path: '/api/agent-api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentMessagesRoute = ApiAgentMessagesRouteImport.update({
  id: '/api/agent-messages',
  path: '/api/agent-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsRoute = ApiAttachmentsRouteImport.update({
  id: '/api/attachments',
  path: '/api/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJwksRoute = ApiJwksRouteImport.update({
  id: '/api/jwks',
  path: '/api/jwks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthDeviceRoute = OauthDeviceRouteImport.update({
  id: '/oauth/device',
  path: '/oauth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTokenRoute = OauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRoute,
} as any)
const AppComputersIndexRoute = AppComputersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppComputersRoute,
} as any)
const AppComputersComputerIdRoute = AppComputersComputerIdRouteImport.update({
  id: '/$computerId',
  path: '/$computerId',
  getParentRoute: () => AppComputersRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppMessagesAgentIdRoute = AppMessagesAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AppMessagesRoute,
} as any)
const ApiAgentAttachmentUploadCapabilitiesRoute =
  ApiAgentAttachmentUploadCapabilitiesRouteImport.update({
    id: '/api/agent/attachment-upload-capabilities',
    path: '/api/agent/attachment-upload-capabilities',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAttachmentsAttachmentIdRoute =
  ApiAttachmentsAttachmentIdRouteImport.update({
    id: '/$attachmentId',
    path: '/$attachmentId',
    getParentRoute: () => ApiAttachmentsRoute,
  } as any)
const ApiInternalCentrifugoRoute = ApiInternalCentrifugoRouteImport.update({
  id: '/api/internal/centrifugo',
  path: '/api/internal/centrifugo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCentrifugoAgentActivityRoute =
  ApiInternalCentrifugoAgentActivityRouteImport.update({
    id: '/api/internal/centrifugo-agent-activity',
    path: '/api/internal/centrifugo-agent-activity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalCentrifugoConnectRoute =
  ApiInternalCentrifugoConnectRouteImport.update({
    id: '/api/internal/centrifugo-connect',
    path: '/api/internal/centrifugo-connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeAvatarRoute = ApiMeAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => ApiMeRoute,
} as any)
const ApiAgentAttachmentsAttachmentIdRoute =
  ApiAgentAttachmentsAttachmentIdRouteImport.update({
    id: '/api/agent/attachments/$attachmentId',
    path: '/api/agent/attachments/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiE2eWorkspacesSlugRoute = ApiE2eWorkspacesSlugRouteImport.update({
  id: '/api/e2e/workspaces/$slug',
  path: '/api/e2e/workspaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/computers': typeof AppComputersRouteWithChildren
  '/messages': typeof AppMessagesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/api/agent-api-keys': typeof ApiAgentApiKeysRoute
  '/api/agent-messages': typeof ApiAgentMessagesRoute
  '/api/attachments': typeof ApiAttachmentsRouteWithChildren
  '/api/jwks': typeof ApiJwksRoute
  '/api/me': typeof ApiMeRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/oauth/device': typeof OauthDeviceRoute
  '/oauth/token': typeof OauthTokenRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/computers/$computerId': typeof AppComputersComputerIdRoute
  '/messages/$agentId': typeof AppMessagesAgentIdRoute
  '/api/agent/attachment-upload-capabilities': typeof ApiAgentAttachmentUploadCapabilitiesRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/internal/centrifugo': typeof ApiInternalCentrifugoRoute
  '/api/internal/centrifugo-agent-activity': typeof ApiInternalCentrifugoAgentActivityRoute
  '/api/internal/centrifugo-connect': typeof ApiInternalCentrifugoConnectRoute
  '/api/me/avatar': typeof ApiMeAvatarRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/computers/': typeof AppComputersIndexRoute
  '/messages/': typeof AppMessagesIndexRoute
  '/api/agent/attachments/$attachmentId': typeof ApiAgentAttachmentsAttachmentIdRoute
  '/api/e2e/workspaces/$slug': typeof ApiE2eWorkspacesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/settings': typeof AppSettingsRoute
  '/api/agent-api-keys': typeof ApiAgentApiKeysRoute
  '/api/agent-messages': typeof ApiAgentMessagesRoute
  '/api/attachments': typeof ApiAttachmentsRouteWithChildren
  '/api/jwks': typeof ApiJwksRoute
  '/api/me': typeof ApiMeRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/oauth/device': typeof OauthDeviceRoute
  '/oauth/token': typeof OauthTokenRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/computers/$computerId': typeof AppComputersComputerIdRoute
  '/messages/$agentId': typeof AppMessagesAgentIdRoute
  '/api/agent/attachment-upload-capabilities': typeof ApiAgentAttachmentUploadCapabilitiesRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/internal/centrifugo': typeof ApiInternalCentrifugoRoute
  '/api/internal/centrifugo-agent-activity': typeof ApiInternalCentrifugoAgentActivityRoute
  '/api/internal/centrifugo-connect': typeof ApiInternalCentrifugoConnectRoute
  '/api/me/avatar': typeof ApiMeAvatarRoute
  '/agents': typeof AppAgentsIndexRoute
  '/computers': typeof AppComputersIndexRoute
  '/messages': typeof AppMessagesIndexRoute
  '/api/agent/attachments/$attachmentId': typeof ApiAgentAttachmentsAttachmentIdRoute
  '/api/e2e/workspaces/$slug': typeof ApiE2eWorkspacesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/_app/computers': typeof AppComputersRouteWithChildren
  '/_app/messages': typeof AppMessagesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/api/agent-api-keys': typeof ApiAgentApiKeysRoute
  '/api/agent-messages': typeof ApiAgentMessagesRoute
  '/api/attachments': typeof ApiAttachmentsRouteWithChildren
  '/api/jwks': typeof ApiJwksRoute
  '/api/me': typeof ApiMeRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/oauth/device': typeof OauthDeviceRoute
  '/oauth/token': typeof OauthTokenRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/_app/computers/$computerId': typeof AppComputersComputerIdRoute
  '/_app/messages/$agentId': typeof AppMessagesAgentIdRoute
  '/api/agent/attachment-upload-capabilities': typeof ApiAgentAttachmentUploadCapabilitiesRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/internal/centrifugo': typeof ApiInternalCentrifugoRoute
  '/api/internal/centrifugo-agent-activity': typeof ApiInternalCentrifugoAgentActivityRoute
  '/api/internal/centrifugo-connect': typeof ApiInternalCentrifugoConnectRoute
  '/api/me/avatar': typeof ApiMeAvatarRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/computers/': typeof AppComputersIndexRoute
  '/_app/messages/': typeof AppMessagesIndexRoute
  '/api/agent/attachments/$attachmentId': typeof ApiAgentAttachmentsAttachmentIdRoute
  '/api/e2e/workspaces/$slug': typeof ApiE2eWorkspacesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/.well-known/oauth-authorization-server'
    | '/computers'
    | '/messages'
    | '/settings'
    | '/api/agent-api-keys'
    | '/api/agent-messages'
    | '/api/attachments'
    | '/api/jwks'
    | '/api/me'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/oauth/device'
    | '/oauth/token'
    | '/agents/$agentId'
    | '/computers/$computerId'
    | '/messages/$agentId'
    | '/api/agent/attachment-upload-capabilities'
    | '/api/attachments/$attachmentId'
    | '/api/internal/centrifugo'
    | '/api/internal/centrifugo-agent-activity'
    | '/api/internal/centrifugo-connect'
    | '/api/me/avatar'
    | '/agents/'
    | '/computers/'
    | '/messages/'
    | '/api/agent/attachments/$attachmentId'
    | '/api/e2e/workspaces/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/.well-known/oauth-authorization-server'
    | '/settings'
    | '/api/agent-api-keys'
    | '/api/agent-messages'
    | '/api/attachments'
    | '/api/jwks'
    | '/api/me'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/oauth/device'
    | '/oauth/token'
    | '/agents/$agentId'
    | '/computers/$computerId'
    | '/messages/$agentId'
    | '/api/agent/attachment-upload-capabilities'
    | '/api/attachments/$attachmentId'
    | '/api/internal/centrifugo'
    | '/api/internal/centrifugo-agent-activity'
    | '/api/internal/centrifugo-connect'
    | '/api/me/avatar'
    | '/agents'
    | '/computers'
    | '/messages'
    | '/api/agent/attachments/$attachmentId'
    | '/api/e2e/workspaces/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/health'
    | '/login'
    | '/.well-known/oauth-authorization-server'
    | '/_app/computers'
    | '/_app/messages'
    | '/_app/settings'
    | '/api/agent-api-keys'
    | '/api/agent-messages'
    | '/api/attachments'
    | '/api/jwks'
    | '/api/me'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/oauth/device'
    | '/oauth/token'
    | '/_app/agents/$agentId'
    | '/_app/computers/$computerId'
    | '/_app/messages/$agentId'
    | '/api/agent/attachment-upload-capabilities'
    | '/api/attachments/$attachmentId'
    | '/api/internal/centrifugo'
    | '/api/internal/centrifugo-agent-activity'
    | '/api/internal/centrifugo-connect'
    | '/api/me/avatar'
    | '/_app/agents/'
    | '/_app/computers/'
    | '/_app/messages/'
    | '/api/agent/attachments/$attachmentId'
    | '/api/e2e/workspaces/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  ApiAgentApiKeysRoute: typeof ApiAgentApiKeysRoute
  ApiAgentMessagesRoute: typeof ApiAgentMessagesRoute
  ApiAttachmentsRoute: typeof ApiAttachmentsRouteWithChildren
  ApiJwksRoute: typeof ApiJwksRoute
  ApiMeRoute: typeof ApiMeRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  OauthDeviceRoute: typeof OauthDeviceRoute
  OauthTokenRoute: typeof OauthTokenRoute
  ApiAgentAttachmentUploadCapabilitiesRoute: typeof ApiAgentAttachmentUploadCapabilitiesRoute
  ApiInternalCentrifugoRoute: typeof ApiInternalCentrifugoRoute
  ApiInternalCentrifugoAgentActivityRoute: typeof ApiInternalCentrifugoAgentActivityRoute
  ApiInternalCentrifugoConnectRoute: typeof ApiInternalCentrifugoConnectRoute
  ApiAgentAttachmentsAttachmentIdRoute: typeof ApiAgentAttachmentsAttachmentIdRoute
  ApiE2eWorkspacesSlugRoute: typeof ApiE2eWorkspacesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/computers': {
      id: '/_app/computers'
      path: '/computers'
      fullPath: '/computers'
      preLoaderRoute: typeof AppComputersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/agent-api-keys': {
      id: '/api/agent-api-keys'
      path: '/api/agent-api-keys'
      fullPath: '/api/agent-api-keys'
      preLoaderRoute: typeof ApiAgentApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-messages': {
      id: '/api/agent-messages'
      path: '/api/agent-messages'
      fullPath: '/api/agent-messages'
      preLoaderRoute: typeof ApiAgentMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments': {
      id: '/api/attachments'
      path: '/api/attachments'
      fullPath: '/api/attachments'
      preLoaderRoute: typeof ApiAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jwks': {
      id: '/api/jwks'
      path: '/api/jwks'
      fullPath: '/api/jwks'
      preLoaderRoute: typeof ApiJwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/device': {
      id: '/oauth/device'
      path: '/oauth/device'
      fullPath: '/oauth/device'
      preLoaderRoute: typeof OauthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/token': {
      id: '/oauth/token'
      path: '/oauth/token'
      fullPath: '/oauth/token'
      preLoaderRoute: typeof OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/computers/': {
      id: '/_app/computers/'
      path: '/'
      fullPath: '/computers/'
      preLoaderRoute: typeof AppComputersIndexRouteImport
      parentRoute: typeof AppComputersRoute
    }
    '/_app/computers/$computerId': {
      id: '/_app/computers/$computerId'
      path: '/$computerId'
      fullPath: '/computers/$computerId'
      preLoaderRoute: typeof AppComputersComputerIdRouteImport
      parentRoute: typeof AppComputersRoute
    }
    '/_app/messages/': {
      id: '/_app/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/_app/messages/$agentId': {
      id: '/_app/messages/$agentId'
      path: '/$agentId'
      fullPath: '/messages/$agentId'
      preLoaderRoute: typeof AppMessagesAgentIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/api/agent/attachment-upload-capabilities': {
      id: '/api/agent/attachment-upload-capabilities'
      path: '/api/agent/attachment-upload-capabilities'
      fullPath: '/api/agent/attachment-upload-capabilities'
      preLoaderRoute: typeof ApiAgentAttachmentUploadCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/$attachmentId': {
      id: '/api/attachments/$attachmentId'
      path: '/$attachmentId'
      fullPath: '/api/attachments/$attachmentId'
      preLoaderRoute: typeof ApiAttachmentsAttachmentIdRouteImport
      parentRoute: typeof ApiAttachmentsRoute
    }
    '/api/internal/centrifugo': {
      id: '/api/internal/centrifugo'
      path: '/api/internal/centrifugo'
      fullPath: '/api/internal/centrifugo'
      preLoaderRoute: typeof ApiInternalCentrifugoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/centrifugo-agent-activity': {
      id: '/api/internal/centrifugo-agent-activity'
      path: '/api/internal/centrifugo-agent-activity'
      fullPath: '/api/internal/centrifugo-agent-activity'
      preLoaderRoute: typeof ApiInternalCentrifugoAgentActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/centrifugo-connect': {
      id: '/api/internal/centrifugo-connect'
      path: '/api/internal/centrifugo-connect'
      fullPath: '/api/internal/centrifugo-connect'
      preLoaderRoute: typeof ApiInternalCentrifugoConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/avatar': {
      id: '/api/me/avatar'
      path: '/avatar'
      fullPath: '/api/me/avatar'
      preLoaderRoute: typeof ApiMeAvatarRouteImport
      parentRoute: typeof ApiMeRoute
    }
    '/api/agent/attachments/$attachmentId': {
      id: '/api/agent/attachments/$attachmentId'
      path: '/api/agent/attachments/$attachmentId'
      fullPath: '/api/agent/attachments/$attachmentId'
      preLoaderRoute: typeof ApiAgentAttachmentsAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/workspaces/$slug': {
      id: '/api/e2e/workspaces/$slug'
      path: '/api/e2e/workspaces/$slug'
      fullPath: '/api/e2e/workspaces/$slug'
      preLoaderRoute: typeof ApiE2eWorkspacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppComputersRouteChildren {
  AppComputersComputerIdRoute: typeof AppComputersComputerIdRoute
  AppComputersIndexRoute: typeof AppComputersIndexRoute
}

const AppComputersRouteChildren: AppComputersRouteChildren = {
  AppComputersComputerIdRoute: AppComputersComputerIdRoute,
  AppComputersIndexRoute: AppComputersIndexRoute,
}

const AppComputersRouteWithChildren = AppComputersRoute._addFileChildren(
  AppComputersRouteChildren,
)

interface AppMessagesRouteChildren {
  AppMessagesAgentIdRoute: typeof AppMessagesAgentIdRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesAgentIdRoute: AppMessagesAgentIdRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppRouteChildren {
  AppComputersRoute: typeof AppComputersRouteWithChildren
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComputersRoute: AppComputersRouteWithChildren,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiAttachmentsRouteChildren {
  ApiAttachmentsAttachmentIdRoute: typeof ApiAttachmentsAttachmentIdRoute
}

const ApiAttachmentsRouteChildren: ApiAttachmentsRouteChildren = {
  ApiAttachmentsAttachmentIdRoute: ApiAttachmentsAttachmentIdRoute,
}

const ApiAttachmentsRouteWithChildren = ApiAttachmentsRoute._addFileChildren(
  ApiAttachmentsRouteChildren,
)

interface ApiMeRouteChildren {
  ApiMeAvatarRoute: typeof ApiMeAvatarRoute
}

const ApiMeRouteChildren: ApiMeRouteChildren = {
  ApiMeAvatarRoute: ApiMeAvatarRoute,
}

const ApiMeRouteWithChildren = ApiMeRoute._addFileChildren(ApiMeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  ApiAgentApiKeysRoute: ApiAgentApiKeysRoute,
  ApiAgentMessagesRoute: ApiAgentMessagesRoute,
  ApiAttachmentsRoute: ApiAttachmentsRouteWithChildren,
  ApiJwksRoute: ApiJwksRoute,
  ApiMeRoute: ApiMeRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  OauthDeviceRoute: OauthDeviceRoute,
  OauthTokenRoute: OauthTokenRoute,
  ApiAgentAttachmentUploadCapabilitiesRoute:
    ApiAgentAttachmentUploadCapabilitiesRoute,
  ApiInternalCentrifugoRoute: ApiInternalCentrifugoRoute,
  ApiInternalCentrifugoAgentActivityRoute:
    ApiInternalCentrifugoAgentActivityRoute,
  ApiInternalCentrifugoConnectRoute: ApiInternalCentrifugoConnectRoute,
  ApiAgentAttachmentsAttachmentIdRoute: ApiAgentAttachmentsAttachmentIdRoute,
  ApiE2eWorkspacesSlugRoute: ApiE2eWorkspacesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
