export type PinnedOpenVikingRoute = {
  method: string;
  path: string;
  family: string;
  classified: false;
};

const route = (method: string, path: string, family: string): PinnedOpenVikingRoute => ({
  method,
  path,
  family,
  classified: false,
});

const WEBDAV_METHODS = [
  "OPTIONS",
  "PROPFIND",
  "GET",
  "HEAD",
  "PUT",
  "DELETE",
  "MKCOL",
  "MOVE",
] as const;

/** D3 pinned inventory. Every row stays unclassified until G3. */
export const PINNED_OPENVIKING_ROUTES: readonly PinnedOpenVikingRoute[] = [
  route("GET", "/health", "health"),
  route("GET", "/ready", "health"),
  route("GET", "/api/v1/system/status", "system"),
  route("POST", "/api/v1/system/wait", "system"),
  route("POST", "/api/v1/system/consistency", "system"),
  route("POST", "/api/v1/system/backend/sync-status", "system"),
  route("POST", "/api/v1/system/backend/sync-retry", "system"),
  route("GET", "/api/v1/system/sync/{sync_path}", "system"),
  route("POST", "/api/v1/system/sync/{sync_path}/retry", "system"),
  route("GET", "/metrics", "metrics"),
  route("GET", "/", "studio"),
  route("GET", "/studio", "studio"),
  route("GET", "/studio/{path}", "studio"),

  route("POST", "/api/v1/resources/temp_upload", "resources"),
  route("POST", "/api/v1/resources", "resources"),
  route("GET", "/api/v1/fs/ls", "filesystem"),
  route("GET", "/api/v1/fs/tree", "filesystem"),
  route("GET", "/api/v1/fs/stat", "filesystem"),
  route("GET", "/api/v1/fs/attrs", "filesystem"),
  route("POST", "/api/v1/fs/attrs/set_tags", "filesystem"),
  route("POST", "/api/v1/fs/mkdir", "filesystem"),
  route("DELETE", "/api/v1/fs", "filesystem"),
  route("POST", "/api/v1/fs/cp", "filesystem"),
  route("POST", "/api/v1/fs/mv", "filesystem"),
  route("GET", "/api/v1/content/read", "content"),
  route("GET", "/api/v1/content/abstract", "content"),
  route("GET", "/api/v1/content/overview", "content"),
  route("GET", "/api/v1/content/download", "content"),
  route("POST", "/api/v1/content/write", "content"),
  route("POST", "/api/v1/content/batch-write", "content"),
  route("POST", "/api/v1/content/set_tags", "content"),
  route("POST", "/api/v1/content/reindex", "content"),
  route("POST", "/api/v1/search/find", "search"),
  route("POST", "/api/v1/search/search", "search"),
  route("POST", "/api/v1/search/recall", "search"),
  route("POST", "/api/v1/search/grep", "search"),
  route("POST", "/api/v1/search/glob", "search"),

  route("GET", "/api/v1/skills", "skill"),
  route("POST", "/api/v1/skills", "skill"),
  route("POST", "/api/v1/skills/find", "skill"),
  route("POST", "/api/v1/skills/validate", "skill"),
  route("GET", "/api/v1/skills/{skill_name}", "skill"),
  route("PUT", "/api/v1/skills/{skill_name}", "skill"),
  route("DELETE", "/api/v1/skills/{skill_name}", "skill"),
  route("POST", "/api/v1/sessions", "session"),
  route("GET", "/api/v1/sessions", "session"),
  route("GET", "/api/v1/sessions/{session_id}", "session"),
  route("PATCH", "/api/v1/sessions/{session_id}/config", "session"),
  route("GET", "/api/v1/sessions/{session_id}/tool-results", "session"),
  route("GET", "/api/v1/sessions/{session_id}/tool-results/{tool_result_id}", "session"),
  route("GET", "/api/v1/sessions/{session_id}/tool-results/{tool_result_id}/search", "session"),
  route("GET", "/api/v1/sessions/{session_id}/context", "session"),
  route("GET", "/api/v1/sessions/{session_id}/archives/{archive_id}", "session"),
  route("DELETE", "/api/v1/sessions/{session_id}", "session"),
  route("POST", "/api/v1/sessions/{session_id}/commit", "session"),
  route("POST", "/api/v1/sessions/{session_id}/extract", "session"),
  route("POST", "/api/v1/sessions/{session_id}/messages", "session"),
  route("POST", "/api/v1/sessions/{session_id}/messages/batch", "session"),
  route("POST", "/api/v1/sessions/{session_id}/used", "session"),
  route("GET", "/api/v1/agent-evolution/experiences/trajectories", "evolution"),
  route("GET", "/api/v1/agent-evolution/experiences/outcomes", "evolution"),
  route("POST", "/api/v1/compile", "compile"),
  route("GET", "/api/v1/compile/capabilities", "compile"),
  route("GET", "/api/v1/compile/submissions/{key}", "compile"),

  route("GET", "/api/v1/tasks", "task"),
  route("GET", "/api/v1/tasks/{task_id}", "task"),
  route("POST", "/api/v1/tasks/{task_id}/cancel", "task"),
  route("GET", "/api/v1/watches", "watch"),
  route("GET", "/api/v1/watches/{task_id}", "watch"),
  route("PATCH", "/api/v1/watches", "watch"),
  route("PATCH", "/api/v1/watches/{task_id}", "watch"),
  route("DELETE", "/api/v1/watches", "watch"),
  route("DELETE", "/api/v1/watches/{task_id}", "watch"),
  route("POST", "/api/v1/watches/trigger", "watch"),
  route("POST", "/api/v1/watches/{task_id}/trigger", "watch"),
  route("POST", "/api/v1/snapshot/commit", "snapshot"),
  route("GET", "/api/v1/snapshot/log", "snapshot"),
  route("POST", "/api/v1/snapshot/restore", "snapshot"),
  route("GET", "/api/v1/snapshot/show", "snapshot"),
  route("GET", "/api/v1/snapshot/diff", "snapshot"),
  route("GET", "/api/v1/snapshot/ignore", "snapshot"),
  route("PUT", "/api/v1/snapshot/ignore", "snapshot"),
  route("DELETE", "/api/v1/snapshot/ignore", "snapshot"),
  route("POST", "/api/v1/pack/export", "pack"),
  route("POST", "/api/v1/pack/import", "pack"),
  route("POST", "/api/v1/pack/backup", "pack"),
  route("POST", "/api/v1/pack/restore", "pack"),
  route("GET", "/api/v1/observer/queue", "observer"),
  route("GET", "/api/v1/observer/vikingdb", "observer"),
  route("GET", "/api/v1/observer/models", "observer"),
  route("GET", "/api/v1/observer/lock", "observer"),
  route("GET", "/api/v1/observer/retrieval", "observer"),
  route("GET", "/api/v1/observer/filesystem", "observer"),
  route("GET", "/api/v1/observer/system", "observer"),
  route("GET", "/api/v1/stats/memories", "stats"),
  route("GET", "/api/v1/stats/sessions/{session_id}", "stats"),

  route("GET", "/api/v1/acl", "acl"),
  route("PUT", "/api/v1/acl", "acl"),
  route("DELETE", "/api/v1/acl", "acl"),
  route("POST", "/api/v1/acl/grant", "acl"),
  route("POST", "/api/v1/acl/revoke", "acl"),
  route("GET", "/api/v1/admin/configuration", "admin"),
  route("PATCH", "/api/v1/admin/configuration", "admin"),
  route("GET", "/api/v1/admin/accounts/{account_id}/configuration", "admin"),
  route("PATCH", "/api/v1/admin/accounts/{account_id}/configuration", "admin"),
  route("GET", "/api/v1/admin/agent-evolution", "admin"),
  route("PUT", "/api/v1/admin/agent-evolution", "admin"),
  route("GET", "/api/v1/admin/accounts/{account_id}/settings", "admin"),
  route("PATCH", "/api/v1/admin/accounts/{account_id}/settings", "admin"),
  route("GET", "/api/v1/admin/accounts/{account_id}/memory-templates", "admin"),
  route("GET", "/api/v1/admin/accounts/{account_id}/memory-templates/{memory_type}", "admin"),
  route("PUT", "/api/v1/admin/accounts/{account_id}/memory-templates/{memory_type}", "admin"),
  route("DELETE", "/api/v1/admin/accounts/{account_id}/memory-templates/{memory_type}", "admin"),
  route("POST", "/api/v1/admin/accounts", "admin"),
  route("GET", "/api/v1/admin/accounts", "admin"),
  route("POST", "/api/v1/admin/migrate", "admin"),
  route("DELETE", "/api/v1/admin/accounts/{account_id}", "admin"),
  route("POST", "/api/v1/admin/accounts/{account_id}/users", "admin"),
  route("GET", "/api/v1/admin/accounts/{account_id}/users", "admin"),
  route("GET", "/api/v1/admin/accounts/{account_id}/users/{user_id}/settings", "admin"),
  route("PATCH", "/api/v1/admin/accounts/{account_id}/users/{user_id}/settings", "admin"),
  route("DELETE", "/api/v1/admin/accounts/{account_id}/users/{user_id}", "admin"),
  route("PUT", "/api/v1/admin/accounts/{account_id}/users/{user_id}/role", "admin"),
  route("POST", "/api/v1/admin/accounts/{account_id}/users/{user_id}/key", "admin"),
  route("POST", "/api/v1/admin/accounts/{account_id}/groups", "admin"),
  route("GET", "/api/v1/admin/accounts/{account_id}/groups", "admin"),
  route("DELETE", "/api/v1/admin/accounts/{account_id}/groups/{group_id}", "admin"),
  route("GET", "/api/v1/admin/accounts/{account_id}/groups/{group_id}/members", "admin"),
  route("PUT", "/api/v1/admin/accounts/{account_id}/groups/{group_id}/members/{user_id}", "admin"),
  route(
    "DELETE",
    "/api/v1/admin/accounts/{account_id}/groups/{group_id}/members/{user_id}",
    "admin",
  ),
  route("GET", "/api/v1/privacy-configs", "privacy"),
  route("GET", "/api/v1/privacy-configs/{category}", "privacy"),
  route("GET", "/api/v1/privacy-configs/{category}/{target_key}", "privacy"),
  route("GET", "/api/v1/privacy-configs/{category}/{target_key}/versions", "privacy"),
  route("GET", "/api/v1/privacy-configs/{category}/{target_key}/versions/{version}", "privacy"),
  route("POST", "/api/v1/privacy-configs/{category}/{target_key}", "privacy"),
  route("POST", "/api/v1/privacy-configs/{category}/{target_key}/activate", "privacy"),

  route("POST", "/api/v1/openviking-assets/resolve", "assets"),
  route("POST", "/api/v1/openviking-assets/preflight", "assets"),
  ...WEBDAV_METHODS.map((method) => route(method, "/webdav/resources", "webdav")),
  ...WEBDAV_METHODS.map((method) => route(method, "/webdav/resources/{resource_path}", "webdav")),
  route("GET", "/mcp", "mcp"),
  route("POST", "/mcp", "mcp"),
  route("DELETE", "/mcp", "mcp"),
  route("GET", "/.well-known/oauth-protected-resource", "oauth"),
  route("GET", "/oauth/authorize/page", "oauth"),
  route("GET", "/oauth/authorize/page/status", "oauth"),
  route("GET", "/api/v1/auth/oauth/pending/{pending_id}", "oauth"),
  route("POST", "/api/v1/auth/oauth-verify", "oauth"),
  route("GET", "/bot/v1/health", "vikingbot"),
  route("POST", "/bot/v1/chat", "vikingbot"),
  route("POST", "/bot/v1/chat/stream", "vikingbot"),
  route("POST", "/bot/v1/feedback", "vikingbot"),
  route("POST", "/bot/v1/compile", "vikingbot"),
  route("GET", "/bot/v1/compile/{task_id}", "vikingbot"),
  route("POST", "/bot/v1/compile/{task_id}/cancel", "vikingbot"),
  route("GET", "/api/v1/admin/bot/capabilities", "vikingbot"),
  route("GET", "/api/v1/admin/accounts/{account_id}/bot/connections", "vikingbot"),
  route("POST", "/api/v1/admin/accounts/{account_id}/bot/connections", "vikingbot"),
  route("GET", "/api/v1/admin/accounts/{account_id}/bot/connections/{connection_id}", "vikingbot"),
  route(
    "PATCH",
    "/api/v1/admin/accounts/{account_id}/bot/connections/{connection_id}",
    "vikingbot",
  ),
  route(
    "DELETE",
    "/api/v1/admin/accounts/{account_id}/bot/connections/{connection_id}",
    "vikingbot",
  ),
  route(
    "POST",
    "/api/v1/admin/accounts/{account_id}/bot/connections/{connection_id}/credentials",
    "vikingbot",
  ),
  route(
    "POST",
    "/api/v1/admin/accounts/{account_id}/bot/connections/{connection_id}/verifications",
    "vikingbot",
  ),
  route(
    "GET",
    "/api/v1/admin/accounts/{account_id}/bot/connections/{connection_id}/conversations",
    "vikingbot",
  ),
  route(
    "GET",
    "/api/v1/admin/accounts/{account_id}/bot/connections/{connection_id}/messages",
    "vikingbot",
  ),
  route("POST", "/api/v1/admin/accounts/{account_id}/bot/onboarding-runs", "vikingbot"),
  route("GET", "/api/v1/admin/accounts/{account_id}/bot/onboarding-runs", "vikingbot"),
  route("GET", "/api/v1/console/dashboard/summary", "console"),
  route("GET", "/api/v1/console/tokens", "console"),
  route("GET", "/api/v1/console/context-commits", "console"),
  route("GET", "/api/v1/console/audit", "console"),
  route("GET", "/api/v1/debug/health", "debug"),
  route("GET", "/api/v1/debug/vector/scroll", "debug"),
  route("GET", "/api/v1/debug/vector/count", "debug"),
  route("GET", "/api/v1/user-settings/add-locations", "user-settings"),
  route("PATCH", "/api/v1/user-settings/add-locations", "user-settings"),
  route("DELETE", "/api/v1/user-settings/add-locations", "user-settings"),
];
