import { chmod, mkdir, rename, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { getLogger } from "@logtape/logtape";

const logger = getLogger(["coforge", "daemon", "code-agent", "git-hook-shims"]);

/**
 * Every client-side git hook name (githooks(5)) plus the server-side ones, which a client
 * repository never triggers but a shim answers harmlessly the same way. `push-to-checkout` is
 * left out on purpose: its mere presence replaces git's built-in `updateInstead` checkout
 * update when something pushes into a local non-bare repository. A pre-2.54 git's
 * `core.hooksPath` (see `git-hooks.ts`) replaces the whole hooks directory, so every name that
 * could plausibly fire needs its own forwarding shim, not only `prepare-commit-msg`.
 */
export const GIT_HOOK_SHIM_NAMES = [
  "applypatch-msg",
  "pre-applypatch",
  "post-applypatch",
  "pre-commit",
  "pre-merge-commit",
  "prepare-commit-msg",
  "commit-msg",
  "post-commit",
  "pre-rebase",
  "post-checkout",
  "post-merge",
  "pre-push",
  "post-rewrite",
  "sendemail-validate",
  "post-index-change",
  "pre-auto-gc",
  "reference-transaction",
  "p4-changelist",
  "p4-prepare-changelist",
  "p4-post-changelist",
  "p4-pre-submit",
  "pre-receive",
  "update",
  "proc-receive",
  "post-receive",
  "post-update",
] as const;

/**
 * A POSIX `sh` shim that stands in for the repository's own hook of the same name. `git`'s
 * `core.hooksPath` points at this whole directory, replacing the repository's own hooks
 * directory, so every shim must forward to whatever hook the repository would otherwise have run
 * (its `.git/hooks` entry, or a repo-local `core.hooksPath` such as husky's `.husky/_`) — this is
 * what keeps `core.hooksPath` injection from silently disabling repository hooks (verified: a
 * lowered `GIT_CONFIG_COUNT` strips this shim directory's own config entries, including its own
 * `core.hooksPath`, so `git rev-parse --git-path hooks` reports the pre-injection answer).
 * `prepare-commit-msg` additionally runs `coforge git prepare-commit-msg` first, ignoring its
 * exit status, since that command is the one CoForge behavior this whole mechanism exists for.
 */
export function gitHookShimScript(name: string): string {
  const runCoforge =
    name === "prepare-commit-msg"
      ? [
          "if command -v coforge >/dev/null 2>&1; then",
          '  coforge git prepare-commit-msg "$@" || true',
          "fi",
          "",
        ].join("\n")
      : "";
  return [
    "#!/bin/sh",
    "# CoForge git hook shim - regenerated by the Daemon, do not edit by hand.",
    `# Forwards to this repository's own "${name}" hook; see git-hook-shims.ts.`,
    "",
    runCoforge,
    'self_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)',
    // A lowered GIT_CONFIG_COUNT strips this shim directory's own config entries (the
    // `core.hooksPath` override included), so this reports the repository's real hooks
    // directory - its `.git/hooks`, or a repo-local override such as husky's `.husky/_`.
    `hooks_dir=$(GIT_CONFIG_COUNT="\${COFORGE_GIT_CONFIG_BASE_COUNT:-0}" git rev-parse --git-path hooks 2>/dev/null) || exit 0`,
    '[ -n "$hooks_dir" ] || exit 0',
    'case "$hooks_dir" in',
    "  /*) resolved_hooks_dir=$hooks_dir ;;",
    '  *) resolved_hooks_dir=$(CDPATH= cd -- "$hooks_dir" 2>/dev/null && pwd) || exit 0 ;;',
    "esac",
    // The repository's real hooks directory resolved back to this shim directory: nothing to
    // forward to, and running the shim again would recurse.
    '[ "$resolved_hooks_dir" = "$self_dir" ] && exit 0',
    `target="$resolved_hooks_dir/${name}"`,
    '[ -x "$target" ] || exit 0',
    'exec "$target" "$@"',
    "",
  ].join("\n");
}

function shimContentDigest(): string {
  const hasher = new Bun.CryptoHasher("sha256");
  for (const name of GIT_HOOK_SHIM_NAMES) hasher.update(`${name}\0${gitHookShimScript(name)}\0`);
  return hasher.digest("hex").slice(0, 16);
}

/** The Daemon's own state/data directory root, matching every other Daemon-owned local store
 * (e.g. `credentials/credential-store.ts`). */
export function daemonHomeDirectory(env: Record<string, string | undefined> = Bun.env): string {
  return env.COFORGE_DAEMON_HOME ?? join(homedir(), ".coforge", "daemon");
}

let ensured: Promise<string | undefined> | undefined;

/** Test-only: clears the memoized shim-directory promise so a fresh probe/write runs again. */
export function resetGitHookShimDirectoryCacheForTests(): void {
  ensured = undefined;
}

/**
 * Idempotently writes the Daemon-owned git hook shim directory used by a pre-2.54 git's
 * `core.hooksPath` injection. The directory name is the shim content's own digest, so a Daemon
 * upgrade that changes shim content writes to a new directory rather than mutating one an
 * already-launched Agent process may have resolved `core.hooksPath` to - "versioned" this way,
 * with no explicit cleanup of older directories needed for correctness. Memoized for the life of
 * this process; returns `undefined` (skip injection, never disable repository hooks) when the
 * directory cannot be prepared.
 */
export async function ensureGitHookShimDirectory(
  root: string = daemonHomeDirectory(),
): Promise<string | undefined> {
  if (!ensured) ensured = build();
  return ensured;

  async function build(): Promise<string | undefined> {
    const directory = join(root, "git-hook-shims", shimContentDigest());
    const marker = join(directory, ".complete");
    try {
      if (await Bun.file(marker).exists()) return directory;
      await mkdir(directory, { recursive: true, mode: 0o700 });
      await chmod(directory, 0o700);
      await Promise.all(
        GIT_HOOK_SHIM_NAMES.map(async (name) => {
          const path = join(directory, name);
          const temporary = `${path}.${crypto.randomUUID()}.tmp`;
          await writeFile(temporary, gitHookShimScript(name), { mode: 0o700 });
          await chmod(temporary, 0o700);
          await rename(temporary, path);
        }),
      );
      await writeFile(marker, "");
      return directory;
    } catch (error) {
      logger.warn("git hook shim directory could not be prepared; hooksPath injection skipped", {
        event: "code-agent.git-hook-shims.write-failed",
        directory,
        error: String(error),
      });
      return undefined;
    }
  }
}
