const allChecks = [
  "agent",
  "cdn-certs",
  "ci",
  "coforge",
  "coforge-sdk",
  "computer",
  "daemon",
  "deploy",
  "installer-crate",
  "macos-lifecycle",
  "oss-cdn",
  "release",
  "web",
  "windows-installer",
  "windows-release",
];

export function selectChecks(paths: string[], track: "changes" | "web" | "local") {
  if (track === "local") {
    // Computer publication does not ship the installer crate, which has its own release.
    return allChecks.filter(
      (check) => !["cdn-certs", "deploy", "installer-crate", "oss-cdn", "web"].includes(check),
    );
  }
  const checks = new Set<string>();
  for (const path of paths) {
    // Only known documentation locations are exempt; source assets (including
    // Markdown prompts) inside application directories may affect runtime behavior.
    if (/^(docs\/|[^/]+\.md$)/.test(path) || /\/(AGENTS|README)\.md$/.test(path)) continue;
    let affected: string[];
    if (path.startsWith("crates/installer/contract/")) {
      // Generated by packages/computer and read back by its tests; the crate reads it too.
      affected = ["computer", "installer-crate"];
    } else if (
      path.startsWith("crates/installer/") ||
      path === "Cargo.toml" ||
      path === "Cargo.lock"
    ) {
      // The crate, and the Cargo workspace root that holds its lockfile and release profile.
      affected = ["installer-crate"];
    } else if (path === "scripts/release/install.ps1") {
      affected = ["release", "web", "windows-installer"];
    } else if (path === "scripts/release/install.sh") {
      affected = ["release", "web"];
    } else if (path.startsWith("apps/web/")) {
      affected = ["web"];
    } else if (/^packages\/(computer|daemon)\/test\/.*\.test\.ts$/.test(path)) {
      affected = [path.split("/")[1]!];
      const nativeTest = /\/(launchd-job|launchd-process|macos-supervisor)\.test\.ts$/;
      if (path.startsWith("packages/daemon/") && nativeTest.test(path)) {
        affected.push("macos-lifecycle");
      }
    } else if (path.startsWith("packages/computer/")) {
      affected = ["computer", "macos-lifecycle", "windows-release"];
    } else if (/^packages\/(agent|cli|coforge|daemon)\//.test(path)) {
      affected = ["computer", "daemon", "macos-lifecycle", "windows-release"];
      if (path.startsWith("packages/agent/")) affected.push("agent", "web");
      if (path.startsWith("packages/coforge/")) affected.push("coforge");
    } else if (path.startsWith("scripts/release/")) {
      affected = ["computer", "daemon", "macos-lifecycle", "release", "windows-release"];
    } else if (path.startsWith("scripts/deploy/") || path.startsWith("infra/")) {
      affected = ["deploy", "web"];
    } else if (/^scripts\/verify-oss-cdn[.]/.test(path)) {
      affected = ["oss-cdn"];
    } else if (path.startsWith("scripts/ops/")) {
      affected = ["cdn-certs"];
    } else {
      // SDK, toolchain, CI, lockfiles, and unclassified new paths get full coverage.
      affected = allChecks;
    }
    // The image copies workspace manifests for its frozen install, even for client packages.
    if (/^(apps|packages)\/[^/]+\/package\.json$/.test(path)) checks.add("web");
    for (const check of affected) checks.add(check);
  }
  if (track === "web") {
    return checks.has("web")
      ? [...(checks.has("ci") ? ["ci"] : []), "deploy", "coforge-sdk", "web"]
      : [];
  }
  return [...checks].sort();
}

if (import.meta.main) {
  const track = Bun.argv[2];
  if (track !== "changes" && track !== "web" && track !== "local") {
    throw new Error("Expected changes, web, or local track");
  }
  const paths = (await Bun.stdin.text()).split("\0").filter(Boolean);
  const checks = selectChecks(paths, track);
  const libraries = checks.filter((check) => ["coforge-sdk", "agent", "coforge"].includes(check));
  const contracts = checks.filter((check) =>
    ["cdn-certs", "ci", "deploy", "release", "oss-cdn"].includes(check),
  );
  const jobs = [
    "changes",
    ...new Set(
      checks.map((check) =>
        libraries.includes(check)
          ? "libraries"
          : contracts.includes(check)
            ? "infrastructure-contracts"
            : check,
      ),
    ),
  ];
  for (const [key, value] of Object.entries({ checks, libraries, contracts, jobs })) {
    console.log(`${key}=${JSON.stringify(value)}`);
  }
  console.log(`deploy=${track === "web" && checks.includes("web")}`);
}
