import { ModelRuntime } from "@earendil-works/pi-coding-agent";
import type { CodeAgentModelMetadata } from "@coforge/protocol";
import { COFORGE_MODEL_PROVIDER_API_KEY_ENV } from "../src/runtime-provider";

const outputPath = new URL("../src/coforge-provider-models.generated.ts", import.meta.url);
const runtime = await ModelRuntime.create({
  modelsPath: null,
  allowModelNetwork: false,
  refreshOnCreate: false,
});

const maximumModels = 200;
const allModels: CodeAgentModelMetadata[] = runtime
  .getModels()
  .filter((model) => Object.hasOwn(COFORGE_MODEL_PROVIDER_API_KEY_ENV, model.provider))
  .map((model) => {
    const thinkingLevelMap = Reflect.get(model, "thinkingLevelMap") as
      | Record<string, unknown>
      | undefined;
    return {
      id: model.id,
      displayName: model.name || model.id,
      description: "",
      modelProvider: model.provider,
      reasoningEfforts: thinkingLevelMap
        ? Object.entries(thinkingLevelMap)
            .filter(([, mapped]) => mapped !== null)
            .map(([level]) => level)
        : model.reasoning
          ? ["off", "minimal", "low", "medium", "high", "xhigh", "max"]
          : [],
      defaultReasoning: "",
      recommended: false,
    };
  })
  .sort((left, right) =>
    `${left.modelProvider}/${left.id}`.localeCompare(`${right.modelProvider}/${right.id}`),
  );

const providerQuota = Math.floor(
  maximumModels / Object.keys(COFORGE_MODEL_PROVIDER_API_KEY_ENV).length,
);
const providerCounts = new Map<string, number>();
const models: CodeAgentModelMetadata[] = [];
const overflow: CodeAgentModelMetadata[] = [];
for (const model of allModels) {
  const count = providerCounts.get(model.modelProvider) ?? 0;
  if (count < providerQuota) {
    models.push(model);
    providerCounts.set(model.modelProvider, count + 1);
  } else {
    overflow.push(model);
  }
}
overflow.sort((left, right) => {
  const leftPriority = left.modelProvider === "openrouter" ? 0 : 1;
  const rightPriority = right.modelProvider === "openrouter" ? 0 : 1;
  return leftPriority - rightPriority;
});
models.push(...overflow.slice(0, maximumModels - models.length));
models.sort((left, right) =>
  `${left.modelProvider}/${left.id}`.localeCompare(`${right.modelProvider}/${right.id}`),
);

const rawSource = `// Generated by scripts/generate-coforge-models.ts. Do not edit.\nimport type { CodeAgentModelMetadata } from "@coforge/protocol";\n\nexport const COFORGE_PROVIDER_MODELS_GENERATED = ${JSON.stringify(models, null, 2)} as const satisfies readonly CodeAgentModelMetadata[];\n`;
const formatter = Bun.spawn(["oxfmt", "--stdin-filepath", outputPath.pathname], {
  stdin: new TextEncoder().encode(rawSource),
  stdout: "pipe",
});
const source = await new Response(formatter.stdout).text();
if ((await formatter.exited) !== 0) throw new Error("Could not format built-in model catalog");

if (Bun.argv.includes("--check")) {
  if ((await Bun.file(outputPath).text()) !== source) {
    console.error("CoForge model catalog is stale; run bun run generate:models");
    process.exit(1);
  }
} else {
  await Bun.write(outputPath, source);
}
