import { ModelRuntime } from "@earendil-works/pi-coding-agent";
import type { CodeAgentModelMetadata } from "@lrm/coforge-sdk/internal";
import { supportedReasoningEfforts } from "#src/reasoning-levels";
import { API_KEY_ENV_BY_PROVIDER } from "#src/runtime-provider";

const outputPath = new URL("../src/coforge-provider-models.generated.ts", import.meta.url);
const runtime = await ModelRuntime.create({
  modelsPath: null,
  allowModelNetwork: false,
  refreshOnCreate: false,
});

const maximumModels = 200;
const allModels: CodeAgentModelMetadata[] = runtime
  .getModels()
  .filter((model) => Object.hasOwn(API_KEY_ENV_BY_PROVIDER, model.provider))
  // A dated snapshot (`claude-haiku-4-5-20251001`) duplicates its undated alias; listing both
  // spends the provider's quota on one model twice.
  .filter((model, _, catalog) => {
    const alias = model.id.replace(/-\d{8}$/u, "");
    return (
      alias === model.id ||
      !catalog.some((other) => other.provider === model.provider && other.id === alias)
    );
  })
  .map((model) => ({
    id: model.id,
    displayName: model.name || model.id,
    description: "",
    modelProvider: model.provider,
    reasoningEfforts: supportedReasoningEfforts(model),
    defaultReasoning: "",
    recommended: false,
  }))
  .sort((left, right) =>
    `${left.modelProvider}/${left.id}`.localeCompare(`${right.modelProvider}/${right.id}`),
  );

// Rounded up so a direct provider with one model past an even share (Anthropic's 13 undated models
// against 200 / 16) keeps its whole line, newest included; OpenRouter still fills what remains.
const providerQuota = Math.ceil(maximumModels / Object.keys(API_KEY_ENV_BY_PROVIDER).length);
const providerCounts = new Map<string, number>();
const models: CodeAgentModelMetadata[] = [];
const overflow: CodeAgentModelMetadata[] = [];
for (const model of allModels) {
  const count = providerCounts.get(model.modelProvider) ?? 0;
  if (count < providerQuota) {
    models.push(model);
    providerCounts.set(model.modelProvider, count + 1);
  } else {
    overflow.push(model);
  }
}
overflow.sort((left, right) => {
  const leftPriority = left.modelProvider === "openrouter" ? 0 : 1;
  const rightPriority = right.modelProvider === "openrouter" ? 0 : 1;
  return leftPriority - rightPriority;
});
models.push(...overflow.slice(0, maximumModels - models.length));
models.sort((left, right) =>
  `${left.modelProvider}/${left.id}`.localeCompare(`${right.modelProvider}/${right.id}`),
);

const rawSource = `// Generated by scripts/generate-coforge-models.ts. Do not edit.\nimport type { CodeAgentModelMetadata } from "@lrm/coforge-sdk/internal";\n\nexport const COFORGE_PROVIDER_MODELS_GENERATED = ${JSON.stringify(models, null, 2)} as const satisfies readonly CodeAgentModelMetadata[];\n`;
const formatter = Bun.spawn(["oxfmt", "--stdin-filepath", outputPath.pathname], {
  stdin: new TextEncoder().encode(rawSource),
  stdout: "pipe",
});
const source = await new Response(formatter.stdout).text();
if ((await formatter.exited) !== 0) throw new Error("Could not format built-in model catalog");

if (Bun.argv.includes("--check")) {
  if ((await Bun.file(outputPath).text()) !== source) {
    console.error("CoForge model catalog is stale; run bun run generate:models");
    process.exit(1);
  }
} else {
  await Bun.write(outputPath, source);
}
